# Project metadata
projectGroup        = team.terrafirmagreg.bot
projectVersion      = 0.3.2
projectName         = TerraFirmaGreg-Bot

# Java compatibility
javaVersion         = 17

# Dependency versions
jdaVersion          = 6.3.0
jsoupVersion        = 1.17.2
gsonVersion         = 2.10.1
dotenvVersion       = 3.0.0
logbackVersion      = 1.5.13
lombokVersion       = 1.18.42

# Plugin versions
shadowPluginVersion = 8.1.1
