# Project metadata
projectGroup        = team.terrafirmagreg.bot
projectVersion      = 0.3.8
projectName         = TerraFirmaGreg-Bot

# Java compatibility
javaVersion         = 25

# Dependency versions
jdaVersion          = 6.4.1
jsoupVersion        = 1.22.2
gsonVersion         = 2.14.0
nightconfigVersion  = 3.8.4
logbackVersion      = 1.5.32
lombokVersion       = 1.18.46

# Plugin versions
shadowPluginVersion = 9.4.2
